services:
  - type: web
    name: mighty-server
    runtime: node
    plan: free # Change to a higher plan if needed
    buildCommand: npm install && npx turbo build --filter=server
    startCommand: npx turbo run generate --filter=database && npm run start --filter=server
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "22"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
      - key: DATABASE_URL
        value: "postgresql://postgres.inxwpmufbiozoykfmweq:HTTgaCvdkvFZ6pfU@aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true"
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://mighty-prime.vercel.app
      - key: PORT
        value: 10000
